---
# tasks file for java-role-nexus
- name: Install Prerequisites
  when: ansible_os_family == "RedHat"
  yum: name={{ item }} state=latest
  loop: [  'java-1.8.0-openjdk', 'java-1.8.0-openjdk-devel' ]
  
- name: install requirements
  when: ansible_os_family == 'Debian'
  apt: name={{item}} state=latest update_cache=true
  loop: [  'openjdk-8-jdk', 'openjdk-8-jre' ]