# ---
# # handlers file for nexus3-oss-role
# ---
# - name: start nexus
#   service: 
#     name: nexus 
#     state: started

# - name: restart nexus
#   service: 
#     name: nexus 
#     state: restarted